# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzo', '0003_auto_20190526_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
